config/routes.rb
Rails.application.routes.draw do
  
  resources :attachments

  resources :posts

  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                      registrations: "registrations"}
  resources :usuario
  post "usuario/follow"
  
  get 'welcome/index'
  root 'welcome#index'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :post
  include Picturable
end

app/models/concerns/picturable.rb
module Picturable
  extend ActiveSupport::Concern
  included do
    after_save :save_image    
  end
  if self.respond_to?(:nombre)
    PATH_FILES = File.join Rails.root, "public", "files", "attachments"
  else
    PATH_FILES = File.join Rails.root, "public", "files", "posts"
  end

  def file=(file)
    unless file.blank?  
        @file = file
        if self.respond_to?(:nombre)
         self.nombre = file.original_filename
        end
        if self.respond_to?(:extension)
        self.extension = file.original_filename.split(".").last.downcase
        end
      end
    end

    def path_file
      File.join PATH_FILES, "#{self.id}.#{self.extension}"
    end

    def has_file?
      File.exists? path_file
    end 

  private
    def save_image
      if @file
        FileUtils.mkdir_p PATH_FILES
        File.open(path_file, "wb") do |f|
          f.write(@file.read)
        end
        @file = nil
      end
    end
end

app/models/concerns/trackable.rb
module Picturable
  extend ActiveSupport::Concern
  included do
    include PublicActivity::Model
    tracked owner: Proc.new{ |controller,model| controller.current_usuario }
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :friend, class_name: "Usuario"
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller,model| controller.current_usuario }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :usuario, dependent: :destroy
  has_many :attachments
  validates :titulo, presence: true, uniqueness: true
  before_save :set_default_price
  include Picturable
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller,model| controller.current_usuario }

  def set_default_price
    self.price ||= 0
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  #devise omniauth_providers: [:facebook, :twitter]

  has_many :posts
  has_many :friendships, foreign_key: "usuario_id", dependent: :destroy
  has_many :follows, through: :friendships, source: :friend
  has_many :followers_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :followers, through: :followers_friendships, source: :usuario

  def follow!(follow_id)
    friendships.create!(friend_id: follow_id)
  end

  def can_follow?(follow_id)
    not follow_id == self.id or friendships.where(friend_id: follow_id).size > 0
  end

  validates :username, presence: true, uniqueness: true, 
  length: {in: 5..20, too_short: "Tiene que tener al menos 5 caracteres.", too_long: "Maximo 20 caracteres."}

  def self.find_or_create_by_omniauth(data)
  	usuario = Usuario.where(provider: data[:provider], uid: data[:uid]).first
  	unless usuario
  		usuario = Usuario.create(
  			nombre: data[:nombre],
  			apellido: data[:apellido],
  			username: data[:username],
  			email: data[:email],
  			uid: data[:uid],
  			provider: data[:provider],
  			password: Devise.friendly_token[0,10]
  			)
  	end
    usuario
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include PublicActivity::StoreController
  protect_from_forgery with: :exception
  
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
	expose(:attachments)
	expose(:attachment, params: :attachment_params)

	def index; end

	def new; end

	def create
		if attachment.save
			redirect_to root_path
		else
			render :new
		end
	end

	private
	def attachment_params
		params.require(:attachment).permit(:nombre, :extension, :post_id, :file)
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
	def facebook
		auth = request.env["omniauth.auth"]
		data = {
			nombre: auth.info.first_name,
			apellido: auth.info.last_name,
			username: "#{auth.info.first_name}#{auth.info.last_name}",
			email: auth.info.email,
			provider: auth.provider,
			uid: auth.uid
		}

		@usuario = Usuario.find_or_create_by_omniauth(data)
		
		if @usuario.persisted?
			sign_in_and_redirect @usuario, event: :authentication
		else
			session[:omniauth_errors] = @usuario.errors.full_messages.to_sentence unless @usuario.save
			session[:omniauth_data] = data

			redirect_to new_usuario_registration_url
		end
	end

	def twitter
		auth = request.env["omniauth.auth"]
		data = {
			nombre: auth.info.name,
			apellido: "",
			username: auth.info.nickname,
			email: "#{auth.info.nickname}@twitter.com",
			provider: auth.provider,
			uid: auth.uid
		}

		@usuario = Usuario.find_or_create_by_omniauth(data)
		
		if @usuario.persisted?
			sign_in_and_redirect @usuario, event: :authentication
		else
			session[:omniauth_errors] = @usuario.errors.full_messages.to_sentence unless @usuario.save
			session[:omniauth_data] = data

			redirect_to new_usuario_registration_url
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_usuario!, except: [:show, :index]

	expose(:posts)	
	expose(:post, attributes: :post_params)

	def index; end

	def show; end

	def new; end

	def edit; end

	def create
		params.permit!
		post.usuario_id = current_usuario.id
		if post.save
			redirect_to root_path
		else
			render :new
		end
	end

	def update
		params.permit!
   respond_to do |format|
     if post.update(post_params)
       format.html { redirect_to post, notice: 'Post was successfully updated.' }
       format.json { head :no_content }
     else
       format.html { render action: 'edit' }
       format.json { render json: post.errors, status: :unprocessable_entity }
     end
   end
  end

	def destroy
		post.destroy
		redirect_to posts_path, notice: "Fue eliminado con exito."
	end

	private
	def post_params
		params.require(:post).permit(:titulo, :contenido, :usuario_id, :file, :price)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		super
	end

	def create
		super
	end

	def update
		super
	end

	private
	def sign_up_params
		params.require(resource_name).permit(:email, :username, :password, :password_confirmation)
	end
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  expose(:follows) { current_usuario.follows }
  expose(:followers) { current_usuario.followers }

  def show
    @usuario = Usuario.find(params[:id])
  end

  def follow
    respond_to do |format|
      if current_usuario.follow!(post_params[:friend_id])
        format.json {head :no_content}
      else
        format.json {render json: "Se encontraron errores", status: :unprocessable_entity}
      end
    end
  end

  private
  def post_params
    params.require(:usuario).permit(:friend_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @actividades = PublicActivity::Activity.all 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_email_oauth
		if session[:omniauth_data]
			session[:omniauth_data][:email]
		else
			""
		end
	end

	def get_username_oauth
		if session[:omniauth_data]
			session[:omniauth_data][:username]
		else
			""
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= form_for(attachment) do |f| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.collection_select :post_id, Post.all, :id,:titulo %>
  </div>

   <div class="actions">
    <%= f.submit "Create Product", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

<%= link_to "Atras", posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>EasyDesign</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert"><%= alert %></p>
	<% end %>
		<header>
			<nav>
				<ul class="nav nav-tabs">
					<li>
						<%= link_to "Inicio", root_path %>
					</li>
					<li>
						<%= link_to "Posts", posts_path %>
					</li>
					<% if usuario_signed_in? %>
					<li>
						<%= link_to "Editar Perfil", edit_usuario_registration_path(current_usuario) %>
					</li>
					<li>
						<%= link_to "Mi Perfil", current_usuario %>
					</li>
					<li style="float: right">
						<%= link_to "Cerrar Session", destroy_usuario_session_path, method: :delete %>
					</li>
					<% else %>
					<li>
						<%= link_to "Ingresar", new_usuario_session_path %>
					</li>
					<li>
						<%= link_to "Registrarse", new_usuario_registration_path %>
					</li>
					<% end %>
				</ul>
			</nav>
		</header>
			<div class="container">
  			<div class="row">
  			
					<%= yield %>

				</div>
			</div>

	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %> <br/>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contenido %> <br/>
    <%= f.text_area :contenido, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %> <br/> 
    <%= f.number_field :price, class: "form-control", step: "any" %>
  </div>
  <div class="form-group">
    <%= f.label :file %> <br/>
    <%= f.file_field :file, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Upload Post", class: "btn btn-info" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', post %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<br>
<ul class="list-group">
	<% posts.each do |post|%>
		<li class="list-group-item">
			<%= link_to post.titulo, post %>
		</li>
	<% end %>
</ul>
<br>
<br>
<% if usuario_signed_in? %>
	<%= link_to 'Crear nuevo post', new_post_path %><br/>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-5 center-block no-float">
  <h1>New Post</h1>
  <%= render 'form' %>
  <%= link_to "Atras", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h1><%= post.titulo %></h1>
  <div>
    <%= post.contenido %>
  </div>
  <div>
    <p>$<%= post.price %></p>
  </div>
</div>
<div class="text-right">
  <% if post.usuario and usuario_signed_in? and post.usuario == current_usuario %>
    <%= link_to 'Editar', edit_post_path(post) %>   
    <%= link_to 'Borrar', post, method: :delete, data: {confirm: "¿Estas seguro de borrar el post?"} %>   
  <% end %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/public_activity/friendship/_create.html.erb
<li class="list-group-item">
  <% if activity.trackable.friend %>
    <%= link_to activity.owner.username, activity.owner %> se hizo amigo de: <%= link_to activity.trackable.friend.username, activity.trackable.friend %>
  <% end %>
</li>

app/views/public_activity/post/_create.html.erb
<li class="list-group-item">
  <%= link_to activity.owner.username, activity.owner %> ha creado un Post: <%= link_to activity.trackable.titulo, activity.trackable %>
</li>

app/views/public_activity/post/_update.html.erb
<li class="list-group-item">
  <%= link_to activity.owner.username, activity.owner %> ha actualizado el Post: <%= link_to activity.trackable.titulo, activity.trackable %>
</li>

app/views/usuario/show.html.erb
<h1><%= @usuario.username.capitalize %></h1>
<% if usuario_signed_in? and current_usuario.can_follow?(@usuario.id) %>
  <button class="btn btn-info" id="follow_btn" data-friend="<%= @usuario.id %>"><i class="fa fa-user"></i>Follow</button>
<% end %>

<% if current_usuario == @usuario %>
  
  <div class="col-md-3">
  <h3>Siguiendo:</h3>
    <ul class="list-group">
      <% follows.each do |follow|%>
        <li class="list-group-item">
          <%= link_to follow.username, follow %>
        </li>
      <% end %>
    </ul>  
  </div>

  <div class="col-md-3">
  <h3>Siguidores:</h3>
    <ul class="list-group">
      <% followers.each do |follower|%>
        <li class="list-group-item">
          <%= link_to follower.username, follower %>
        </li>
      <% end %>
    </ul>  
  </div>
<% end %>

app/views/welcome/index.html.erb
<div class="col-md-6 center-block no-float">
  <h1>Bienvenido :)</h1>
  <ul class="list-group">
    <% if usuario_signed_in? %>
      <%= render_activities(@actividades) %>
    <% end %>
  </ul>
</div>